### ISSUE TITLE
Dead link in readme

### ISSUE THREAD

**Issue by debugger22** [pote/planet.rb#49]
> This gem is also [gloriously untested](http://jamiesharpe.info/image/comics/haters/haters_gonna_hate3.jpg) so I will assume that each time we use it a TDD enthusiast's head explodes.

This one untested too. :)

How about replacing with this one?

![no-alt](http://i1001.photobucket.com/albums/af138/cypcode/Funny%20Stuff/haters_gonna_hate3.jpg)

**Comment by pote** [comment]
That image link broke like a million times already. :dancer: 

+1 to include it in the repo and be done with it, but I defer to @sauron who is currently maintaining Planet. :)

**Comment by sauron** [comment]
Ha!
@debugger22 Nice picture! Including it right now!
But hopefully it wouldn't last long :trollface: 

brb, changing a picture!
