### ISSUE TITLE
Broken with ruby2.0?

### ISSUE THREAD

**Issue by laurivosandi** [pote/planet.rb#50]
Hi,

I did ```apt-get install ruby2.0 ruby2.0-dev``` and ```gem2.0 install planet``` on Debian 8 (jessie). I am greeted with following error message while I run ```planet generate```:

```
Error: undefined method `URI' for #<Planet::Parsers:0x00000001a7d6f8 @domains={}, @types={}> (NoMethodError)
/var/lib/gems/2.0.0/gems/planet-0.5.4/lib/planet/parsers.rb:49:in `get_parser_for'
/var/lib/gems/2.0.0/gems/planet-0.5.4/lib/planet/blog.rb:45:in `fetch'
/var/lib/gems/2.0.0/gems/planet-0.5.4/lib/planet.rb:24:in `block in aggregate'
/var/lib/gems/2.0.0/gems/planet-0.5.4/lib/planet.rb:22:in `each'
/var/lib/gems/2.0.0/gems/planet-0.5.4/lib/planet.rb:22:in `aggregate'
/var/lib/gems/2.0.0/gems/planet-0.5.4/lib/planet/importer.rb:5:in `import'
/var/lib/gems/2.0.0/gems/planet-0.5.4/bin/planet:26:in `block (2 levels) in <top (required)>'
/var/lib/gems/2.0.0/gems/gli-2.13.1/lib/gli/command_support.rb:126:in `call'
/var/lib/gems/2.0.0/gems/gli-2.13.1/lib/gli/command_support.rb:126:in `execute'
/var/lib/gems/2.0.0/gems/gli-2.13.1/lib/gli/app_support.rb:296:in `block in call_command'
/var/lib/gems/2.0.0/gems/gli-2.13.1/lib/gli/app_support.rb:309:in `call'
/var/lib/gems/2.0.0/gems/gli-2.13.1/lib/gli/app_support.rb:309:in `call_command'
/var/lib/gems/2.0.0/gems/gli-2.13.1/lib/gli/app_support.rb:83:in `run'
/var/lib/gems/2.0.0/gems/planet-0.5.4/bin/planet:140:in `<top (required)>'
/usr/local/bin/planet:23:in `load'
/usr/local/bin/planet:23:in `<main>'
error: undefined method `URI' for #<Planet::Parsers:0x00000001a7d6f8 @domains={}, @types={}>
```

**Comment by laurivosandi** [comment]
Attempting to install with Ruby 1.9.1 I am greeted with following error message:

```
Installing gem mustache-1.0.2
ERROR:  Error installing planet:
	mustache requires Ruby version ~> 2.0.
```

**Comment by ryanakca** [comment]
I can confirm that this is still an issue under ruby 2.2.0.

**Comment by pote** [comment]
I'll take a look at the ruby 2.0 and 2.2 issues, it's important to note however that ruby 1.9.3 and lower have reached end of life and [are not supported by the ruby core team anymore](https://www.ruby-lang.org/en/news/2014/01/10/ruby-1-9-3-will-end-on-2015/), so don't keep your hopes up for planet to work on them.

**Comment by sauron** [comment]
Hello,
I've just noticed that I somehow missed these notifications.
@pote let me know if you are working on a fix. If not I'll do it in a bit.

Best.

**Comment by pote** [comment]
Not looking at it yet! If you have a moment for it it'd be great, if not I'll try to make some time to at least get it to run on 2.2. :)

**Comment by sauron** [comment]
Just FYI I've merged a proposed fix for this.
I've already tested on the following rubies on Mac OSx
Ruby 2.1
Ruby 2.2
Ruby 2.3
Will test it on Linux later today and if everything works I'll release a new version.

**Comment by sauron** [comment]
Tested on Linux and it works!
A new release it's coming!!!

**Comment by pote** [comment]
:boom: great job! Thanks @sauron! :tada: :dancer: :balloon:
